import "./scss/globals.scss";
import type { Metadata, Viewport } from "next";
import Header from "@/components/default/header/Header";
import { AuthProvider } from "@/guards/auth.guard";

export const metadata: Metadata = {
  title: "Fingers App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
